name: Test
on:
  push:
    branches:
      - master
jobs:
  tests:
    name: Tests
    strategy:
      matrix:
        php-version:
          - "7.2"
          - "7.3"
          - "7.4"
        operating-system: [ubuntu-latest]

    runs-on: ${{ matrix.operating-system }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Get Composer Cache Directory
        id: composer-cache
        run: |
          echo "::set-output name=dir::$(composer config cache-files-dir)"
      - uses: actions/cache@v2
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-php-${{ matrix.php-version }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-php-${{ matrix.php-version }}-composer-
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite,json,redis
          coverage: none
      - name: Install Composer dependencies
        run: composer install --prefer-dist --no-interaction --no-suggest
      - name: Copy ENV Configuration for CI
        run: php -r "file_exists('.env') || copy('.env.ci', '.env');"
      - name: Create DB and schemas
        run: |
            mkdir -p database
            touch database/database.sqlite
            php artisan migrate
      - name: Execute tests (Unit and Feature tests) via PHPUnit
        run: vendor/bin/phpunit
